#!/usr/bin/env node

'use strict';

const R = require('ramda');

const _ = R.__;

R.pipe(
  R.drop(2),
  R.reverse,
  R.map(R.concat('../')),
  R.map(require),
  R.map(R.toPairs),
  R.reduce(R.concat, []),
  R.uniqBy(R.head),
  R.sortBy(R.head),
  R.map(R.adjust(R.concat(['error']), 1)),
  R.map(R.map(R.toString)),
  R.map(R.join(': ')),
  R.join(',\n    '),
  R.replace('"x": 1', _, JSON.stringify({rules: {x: 1}}, null, 2)),
  R.concat(_, '\n'),
  s => { process.stdout.write(s); }
)(process.argv);
